version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: task-the-movie-db
    path: ""
    text-resources:
      - path: "*.tsx"
        format: react-hardcoded
