os: linux
language: node_js
node_js:
  - "10"
install:
  - npm install
cache:
  directories:
  - node_modules
script:
  - npm test
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  edge: true
  provider: pages
  cleanup: true
  keep_history: false
  github_token: $GITHUB_AUTH_TOKEN
  local_dir: src
  verbose: true
  on:
    branch: master